#!/usr/bin/env bash

set -euo pipefail

kompile --gen-bison-parser metamath.md --output-definition .build/metamath

mkdir -p .build/metamath-parsed/
for f in deps/metamath/theory/*.mm; do
    echo "$f"
    krun "$f" --definition .build/metamath > ".build/metamath-parsed/$(basename $f)"
done
