#!/usr/bin/env bash

set -euo pipefail

test-parse-metamath() {
    kompile --gen-bison-parser metamath.md --output-definition .build/metamath
    mkdir -p .build/metamath-parsed/
    for f in deps/metamath/theory/*.mm; do
        echo "Parsing: $f"
        krun "$f" --definition .build/metamath > ".build/metamath-parsed/$(basename $f)"
    done
}

test-parse-high-level-ml() {
    kompile --gen-bison-parser matching-logic.md -o .build/matching-logic
    krun --definition .build/matching-logic ./prelude.matching-logic
}

test-prelude-to-metamath() {
    kompile --gen-bison-parser matching-logic-to-metamath.md -o .build/matching-logic-to-metamath
    krun --definition .build/matching-logic-to-metamath ./prelude.matching-logic
}

test-parse-metamath
test-parse-high-level-ml
test-prelude-to-metamath
